Hw02 express
marlenaduleba/goit-nodejs-hw-02-06 pull request #1
Opened 2023-06-05 19:23 UTC by marlenaduleba

2023-06-06 15:58 UTC, artemzubchenko requested changes
Proszę o tych drobnych naprawieniach!

2023-06-06 15:58 UTC, artemzubchenko commented on app.js
> +app.use("/contacts", contactsRouter);
Proszę o powrocie do ścieżki **/api/**

2023-06-06 15:58 UTC, artemzubchenko commented on routes/api/contacts.js
> +        result,
Proszę przy DELETE dodać jakiś komunikat, że element został usunięty! Mówię i o innych: POST itd.

2023-06-09 12:03 UTC, marlenaduleba commented on app.js
> +app.use("/contacts", contactsRouter);
Poprawione

2023-06-09 12:03 UTC, marlenaduleba commented on routes/api/contacts.js
> +        result,
Poprawione

2023-06-10 11:20 UTC, artemzubchenko approved these changes
Teraz jest super! Proszę o merge :)

2023-06-10 11:26 UTC, merged